# Generated by Django 4.0.3 on 2022-03-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0002_remove_fileupload_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
